# Generated by Django 6.0.3 on 2026-03-15 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('npi', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NPI must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('specialty', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Provider',
                'indexes': [models.Index(fields=['npi'], name='provider_npi_idx')],
            },
        ),
    ]
